# Generated by Django 3.2 on 2021-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(max_length=10, verbose_name='contact'),
        ),
    ]
