# Generated by Django 3.2 on 2021-05-09 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AOU', to=settings.AUTH_USER_MODEL)),
                ('subAou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subAOU', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
