# Generated by Django 3.2 on 2021-05-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_superpower',
            new_name='is_superuser',
        ),
    ]
