# Generated by Django 3.2 on 2021-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210515_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_aou',
            field=models.BooleanField(default=False),
        ),
    ]
