# Generated by Django 3.2.4 on 2021-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('ON', 'Opened'), ('WIP', 'Work in Progress'), ('RE', 'Resolved'), ('URE', 'Unresolved')], default='ON', max_length=3)),
            ],
        ),
    ]
