# Generated by Django 3.2.4 on 2021-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
