# Generated by Django 3.2.6 on 2021-09-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='relTo',
            field=models.CharField(default='Other', max_length=100, null=True),
        ),
    ]
