# Generated by Django 3.2 on 2021-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_couponcustomer_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcustomer',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
