# Generated by Django 3.0.3 on 2021-10-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20211024_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
