# Generated by Django 3.0.3 on 2021-10-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_stripecustomer_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='flag',
            new_name='Activated',
        ),
    ]
