# Generated by Django 3.0.3 on 2021-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20211028_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='Activated',
            new_name='activated',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='pervious_plan',
            field=models.CharField(blank=True, choices=[('TR', 'Trial'), ('SU', 'Single User'), ('CU', 'Community')], max_length=2),
        ),
    ]
