# Generated by Django 3.0.3 on 2021-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20211028_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='plan',
            field=models.CharField(blank=True, choices=[('TR', 'Trial'), ('SU', 'Single User'), ('CU', 'Community')], max_length=2),
        ),
    ]
