# Generated by Django 3.0.3 on 2021-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20211028_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripeSubscriptionsId',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
