# Generated by Django 3.0.3 on 2021-10-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_stripecustomer_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcustomer',
            name='plan',
            field=models.CharField(choices=[('TR', 'Trial'), ('TH', 'Three days'), ('SU', 'Single User'), ('CU', 'Community')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='pervious_plan',
            field=models.CharField(blank=True, choices=[('TR', 'Trial'), ('TH', 'Three days'), ('SU', 'Single User'), ('CU', 'Community')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='plan',
            field=models.CharField(blank=True, choices=[('TR', 'Trial'), ('TH', 'Three days'), ('SU', 'Single User'), ('CU', 'Community')], max_length=2),
        ),
    ]
